const tableMock = [
  {
    id: 1,
    workingDayAm: "AM",
    workingDayPm: "PM",
    day: "Lunes",
    placeHolderAm: "--:--",
    nameAm: "",
    disabledAm: true,
    hiddenEdit: true,
    edit: false,
    readOnly: true,
    checkedPm: false,
  },
  {
    id: 2,
    workingDayAm: "AM",
    workingDayPm: "PM",
    day: "Martes",
    placeHolderAm: "--:--",
    nameAm: "",
    disabledAm: true,
    hiddenEdit: true,
    edit: false,
    readOnly: true,
    checkedPm: false,
  },
  {
    id: 3,
    workingDayAm: "AM",
    workingDayPm: "PM",
    day: "Miercoles",
    placeHolderAm: "--:--",
    nameAm: "",
    disabledAm: true,
    hiddenEdit: true,
    edit: false,
    readOnly: true,
    checkedPm: false,
  },
  {
    id: 4,
    workingDayAm: "AM",
    workingDayPm: "PM",
    day: "Jueves",
    placeHolderAm: "--:--",
    nameAm: "",
    disabledAm: true,
    hiddenEdit: true,
    edit: false,
    readOnly: true,
    checkedPm: false,
  },
  {
    id: 5,
    workingDayAm: "AM",
    workingDayPm: "PM",
    day: "Viernes",
    placeHolderAm: "--:--",
    nameAm: "",
    disabledAm: true,
    hiddenEdit: true,
    edit: false,
    readOnly: true,
    checkedPm: false,
  },
  {
    id: 6,
    workingDayAm: "AM",
    workingDayPm: "PM",
    day: "Sabado",
    placeHolderAm: "--:--",
    nameAm: "",
    disabledAm: true,
    hiddenEdit: true,
    edit: false,
    readOnly: true,
    checkedPm: false,
  },
  {
    id: 0,
    workingDayAm: "AM",
    workingDayPm: "PM",
    day: "Domingo",
    placeHolderAm: "--:--",
    nameAm: "",
    disabledAm: true,
    hiddenEdit: true,
    edit: false,
    readOnly: true,
    checkedPm: false,
  },
];

export default tableMock;
