version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  version: 2      
      #cron: "0 0 */6 ? * *" #0 0 * * *"
      filters:
        branches:
          only:
            - master
            - develop
  build-and-test:
    jobs:
      - build-and-test
